# Tahapan Preprocessing Data

Notebook ini berisi langkah-langkah preprocessing data untuk mempersiapkan dataset sebelum digunakan dalam analisis atau pemodelan. Setiap tahapan akan dijelaskan input dan output yang diharapkan.

## Import Library
**Input:** Tidak ada input langsung, hanya mengimpor library yang diperlukan.

**Output:** Library seperti pandas, numpy, dan re siap digunakan untuk manipulasi data dan operasi lainnya.

In [4]:
import pandas as pd
import numpy as np
import re

## Membaca Dataset
**Input:** File CSV `../output/bajuWanita_enriched.csv` yang berisi data mentah.

**Output:** DataFrame `df` yang memuat data dari file CSV, siap untuk diproses lebih lanjut.

In [5]:
df = pd.read_csv("../olahData/gabungan_dataset.csv")
print(df.shape)
df.head()

(128503, 26)

,id,name,url,category_breadcrumb,price_number,price_original,discountPercentage,mediaURL_image,mediaURL_image_fixed,ratingAverage,...,isTopAds,labelGroups,label_titles,totalRating,countReview,image_status,image_source,image_local_path,source_file,category
0,102092883266,(Free Kotak)Ikat Rambut Jepit Rambut Set Anak ...,https://www.tokopedia.com/blissow-tk/free-kota...,fashion-anak-bayi/aksesoris-anak/ikat-rambut-anak,98450,Rp179.000,0,https://p16-images-common-sign-sg.tokopedia-st...,https://p16-images-common-sign-sg.tokopedia-st...,4.8,...,False,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Hemat s.d 1% Pakai Bonus | 45%...,203.0,80.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1020928832...,aksesoriAnak_enriched.csv,aksesoriAnak
1,6191416839,Ikat Rambut Karet Pita Anak 18 in 1 Jepit Ramb...,https://www.tokopedia.com/tokomixnmax/ikat-ram...,fashion-anak-bayi/aksesoris-anak/pita-rambut-anak,19990,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.9,...,False,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Hemat s.d 1% Pakai Bonus | Rp1...,338.0,50.0,200.0,refreshed,output\aksesoriAnak_enriched_images\6191416839...,aksesoriAnak_enriched.csv,aksesoriAnak
2,12451070010,Shinemi - 14pcs / Set Jepitan Rambut Anak Fash...,https://www.tokopedia.com/universalcs/shinemi-...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,9845,Rp9.999,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,...,False,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Campaign | Hemat s.d 1% Pakai ...,349.0,61.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1245107001...,aksesoriAnak_enriched.csv,aksesoriAnak
3,102098465697,Leletoys Paket Lengkap Mainan DIY Tangan untuk...,https://www.tokopedia.com/lele-toys-online-mal...,rumah-tangga/furniture/cermin-badan,50100,Rp103.200,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,5.0,...,False,"[{""position"": ""ri_product_credibility"", ""title...",60+ terjual | Campaign | Hemat s.d 1% Pakai B...,7.0,2.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1020984656...,aksesoriAnak_enriched.csv,aksesoriAnak
4,100082586008,ByKiddos - Set Aksesories Rambut Anak Isi 18 P...,https://www.tokopedia.com/bykiddos/bykiddos-se...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,22900,Rp39.000,0,https://p16-images-common-sign-sg.tokopedia-st...,https://p16-images-common-sign-sg.tokopedia-st...,4.8,...,False,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Bisa COD | 41% | Rp22.900 | Bis...,180.0,127.0,403.0,NaN,NaN,aksesoriAnak_enriched.csv,aksesoriAnak

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128503 entries, 0 to 128502
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    128503 non-null  int64
 1   name                  128503 non-null  object
 2   url                   128503 non-null  object
 3   category_breadcrumb   128478 non-null  object
 4   price_number          128503 non-null  int64
 5   price_original        68983 non-null   object
 6   discountPercentage    128503 non-null  int64
 7   mediaURL_image        128503 non-null  object
 8   mediaURL_image_fixed  128496 non-null  object
 9   ratingAverage         128477 non-null  float64
 10  shop_id               128503 non-null  int64
 11  shop_name             128503 non-null  object
 12  shop_url              128503 non-null  object
 13  shop_city             128117 non-null  object
 14  shop_tier             128503 non-null  int64
 15  countSold             117474 non-null  float64
 16  isTopAds              128503 non-null  bool
 17  labelGroups           128503 non-null  object
 18  label_titles          128495 non-null  object
 19  totalRating           128436 non-null  float64
 20  countReview           128436 non-null  float64
 21  image_status          125256 non-null  float64
 22  image_source          109577 non-null  object
 23  image_local_path      109577 non-null  object
 24  source_file           128503 non-null  object
 25  category              128503 non-null  object
dtypes: bool(1), float64(5), int64(5), object(15)
memory usage: 24.6+ MB

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumns:")
print(df.columns.tolist())

Rows: 128503
Columns: 26

Columns:
['id', 'name', 'url', 'category_breadcrumb', 'price_number', 'price_original', 'discountPercentage', 'mediaURL_image', 'mediaURL_image_fixed', 'ratingAverage', 'shop_id', 'shop_name', 'shop_url', 'shop_city', 'shop_tier', 'countSold', 'isTopAds', 'labelGroups', 'label_titles', 'totalRating', 'countReview', 'image_status', 'image_source', 'image_local_path', 'source_file', 'category']

In [17]:
print("\nDescriptive Statistics:")
print(df.describe(include="all"))

Descriptive Statistics:
                  id                                               name  \
count   1.285030e+05                                             128503
unique           NaN                                             119193
top              NaN  ZHONGSANQING Pembersih multifungsi bersih seke...
freq             NaN                                                 34
mean    1.212368e+14                                                NaN
std     1.447667e+16                                                NaN
min     1.216982e+06                                                NaN
25%     1.000129e+11                                                NaN
50%     1.002738e+11                                                NaN
75%     1.020985e+11                                                NaN
max     1.730708e+18                                                NaN

                                                      url  \
count                                              128503
unique                                             128503
top     https://www.tokopedia.com/blissow-tk/free-kota...
freq                                                    1
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                           category_breadcrumb  price_number price_original  \
count                                   128478  1.285030e+05          68983
unique                                    2173           NaN           8381
top     makanan-minuman/makanan-ringan/keripik           NaN      Rp150.000
freq                                      2328           NaN           1501
mean                                       NaN  2.706389e+06            NaN
std                                        NaN  5.773643e+07            NaN
min                                        NaN  1.000000e+02            NaN
25%                                        NaN  2.500000e+04            NaN
50%                                        NaN  5.700000e+04            NaN
75%                                        NaN  1.335350e+05            NaN
max                                        NaN  2.000000e+09            NaN

        discountPercentage                                     mediaURL_image  \
count             128503.0                                             128503
unique                 NaN                                             128363
top                    NaN  https://p16-images-sign-sg.tokopedia-static.ne...
freq                   NaN                                                  4
mean                   0.0                                                NaN
std                    0.0                                                NaN
min                    0.0                                                NaN
25%                    0.0                                                NaN
50%                    0.0                                                NaN
75%                    0.0                                                NaN
max                    0.0                                                NaN

                                     mediaURL_image_fixed  ratingAverage  ...  \
count                                              128496  128477.000000  ...
unique                                             128356            NaN  ...
top     https://p16-images-sign-sg.tokopedia-static.ne...            NaN  ...
freq                                                    4            NaN  ...
mean                                                  NaN       4.089369  ...
std                                                   NaN       1.699630  ...
min                                                   NaN       0.000000  ...
25%                                                   NaN       4.600000  ...
50%                                                   NaN       4.800000  ...
75%                                                   NaN       4.900000  ...
max                                                   NaN       5.000000  ...

        isTopAds                                        labelGroups  \
count     128503                                             128503
unique         1                                             106767
top        False  [{"position": "ri_product_offer", "title": "Bi...
freq      128503                                                 81
mean         NaN                                                NaN
std          NaN                                                NaN
min          NaN                                                NaN
25%          NaN                                                NaN
50%          NaN                                                NaN
75%          NaN                                                NaN
max          NaN                                                NaN

                          label_titles    totalRating    countReview  \
count                           128495  128436.000000  128436.000000
unique                          105231            NaN            NaN
top     Bisa COD | Rp15.000 | Bisa COD            NaN            NaN
freq                                81            NaN            NaN
mean                               NaN    1068.366720     410.845643
std                                NaN    5559.798107    1600.062425
min                                NaN       0.000000       0.000000
25%                                NaN       5.000000       3.000000
50%                                NaN      83.000000      47.000000
75%                                NaN     522.000000     244.000000
max                                NaN  453538.000000  116322.000000

         image_status image_source  \
count   125256.000000       109577
unique            NaN            2
top               NaN    refreshed
freq              NaN       109429
mean       213.769983          NaN
std         51.666848          NaN
min         -1.000000          NaN
25%        200.000000          NaN
50%        200.000000          NaN
75%        200.000000          NaN
max        504.000000          NaN

                                         image_local_path  \
count                                              109577
unique                                             109577
top     output\aksesoriAnak_enriched_images\1020928832...
freq                                                    1
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                    source_file    category
count                    128503      128503
unique                       74          74
top     kainDaerah_enriched.csv  kainDaerah
freq                       2284        2284
mean                        NaN         NaN
std                         NaN         NaN
min                         NaN         NaN
25%                         NaN         NaN
50%                         NaN         NaN
75%                         NaN         NaN
max                         NaN         NaN

[11 rows x 26 columns]

In [18]:
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
id                          0
name                        0
url                         0
category_breadcrumb        25
price_number                0
price_original          59520
discountPercentage          0
mediaURL_image              0
mediaURL_image_fixed        7
ratingAverage              26
shop_id                     0
shop_name                   0
shop_url                    0
shop_city                 386
shop_tier                   0
countSold               11029
isTopAds                    0
labelGroups                 0
label_titles                8
totalRating                67
countReview                67
image_status             3247
image_source            18926
image_local_path        18926
source_file                 0
category                    0
dtype: int64

## Mengecek dan Menghapus Duplikat
**Input:** DataFrame `df` dengan kolom `id`.

**Output:** Jumlah baris duplikat berdasarkan kolom `id` dan DataFrame `df` tanpa baris duplikat.

In [20]:
# =========================
# Hitung jumlah duplikat berdasarkan 'id'
# =========================
duplicated_rows_count = df.duplicated(subset=["id"]).sum()
duplicated_id_count = df.loc[df.duplicated(subset=["id"], keep=False), "id"].nunique()
total_rows_in_duplicate_groups = df.duplicated(subset=["id"], keep=False).sum()

print(f"Jumlah baris duplikat berdasarkan 'id'        : {duplicated_rows_count}")
print(f"Jumlah nilai 'id' yang terduplikasi           : {duplicated_id_count}")
print(f"Total baris yang termasuk grup duplikat 'id'  : {total_rows_in_duplicate_groups}")

Jumlah baris duplikat berdasarkan 'id'        : 6857
Jumlah nilai 'id' yang terduplikasi           : 6011
Total baris yang termasuk grup duplikat 'id'  : 12868

In [21]:
# =========================
# Tampilkan semua baris yang memiliki 'id' duplikat
# =========================
dup_rows = (
    df[df.duplicated(subset=["id"], keep=False)]
    .sort_values(by=["id"])
    .copy()
)

print("\nContoh baris duplikat berdasarkan 'id':")
print(dup_rows.head(20))

Contoh baris duplikat berdasarkan 'id':
              id                                               name  \
79466    1652218  Petis Botol Yudhistira ORIGINAL Siap Saji Khas...
65288    1652218  Petis Botol Yudhistira ORIGINAL Siap Saji Khas...
80471    6652088  Keripik Maicih Basreng Level 10 Pedas Rempah O...
60715    6652088  Keripik Maicih Basreng Level 10 Pedas Rempah O...
10093    7823934                Bahan Aksesoris Kait Kalung Tembaga
7996     7823934                Bahan Aksesoris Kait Kalung Tembaga
7976     7823984                   Bahan Aksesoris Kait Kalung Gold
10084    7823984                   Bahan Aksesoris Kait Kalung Gold
92128   32114907         Logam Mulia Antam 10 Gram Sertifikat Press
8155    32114907         Logam Mulia Antam 10 Gram Sertifikat Press
88795   34691701                             jacket anak semi kulit
86590   34691701                             jacket anak semi kulit
64620   34752708                 pin protokol indonesia atau daerah
54451   34752708                 pin protokol indonesia atau daerah
53734   37523721  Otonomi Daerah : Filosofi, Sejarah Perkembanga...
64544   37523721  Otonomi Daerah : Filosofi, Sejarah Perkembanga...
73664   40888941  Keripik Singkong Turbo Sakti 130gr Rasa Bawang...
60520   40888941  Keripik Singkong Turbo Sakti 130gr Rasa Bawang...
126902  46298536  Hepamax 30 Softgel - Suplemen Pelindung Fungsi...
61631   46298536  Hepamax 30 Softgel - Suplemen Pelindung Fungsi...

                                                      url  \
79466   https://www.tokopedia.com/tahupetis/petis-siap...
65288   https://www.tokopedia.com/tahupetis/petis-siap...
80471   https://www.tokopedia.com/geraisnackofficial/k...
60715   https://www.tokopedia.com/geraisnackofficial/k...
10093   https://www.tokopedia.com/de-mote/bahan-akseso...
7996    https://www.tokopedia.com/de-mote/bahan-akseso...
7976    https://www.tokopedia.com/de-mote/bahan-akseso...
10084   https://www.tokopedia.com/de-mote/bahan-akseso...
92128   https://www.tokopedia.com/indo-gold/emas-antam...
8155    https://www.tokopedia.com/indo-gold/emas-antam...
88795   https://www.tokopedia.com/eriztacollection/jac...
86590   https://www.tokopedia.com/eriztacollection/jac...
64620   https://www.tokopedia.com/etsacentro/pin-proto...
54451   https://www.tokopedia.com/etsacentro/pin-proto...
53734   https://www.tokopedia.com/socialagencybaru/oto...
64544   https://www.tokopedia.com/socialagencybaru/oto...
73664   https://www.tokopedia.com/tokoebok/kripik-sing...
60520   https://www.tokopedia.com/tokoebok/kripik-sing...
126902  https://www.tokopedia.com/sahabatkesehatan/hep...
61631   https://www.tokopedia.com/sahabatkesehatan/hep...

                                  category_breadcrumb  price_number  \
79466       makanan-minuman/bumbu-bahan-masakan/kecap         42000
65288       makanan-minuman/bumbu-bahan-masakan/kecap         42000
80471          makanan-minuman/makanan-ringan/keripik         18900
60715          makanan-minuman/makanan-ringan/keripik         18900
10093   fashion-wanita/perhiasan-wanita/kalung-wanita           650
7996    fashion-wanita/perhiasan-wanita/kalung-wanita           650
7976    fashion-wanita/perhiasan-wanita/kalung-wanita           650
10084   fashion-wanita/perhiasan-wanita/kalung-wanita           650
92128                                     logam-mulia      35663800
8155                                      logam-mulia      35042400
88795          fashion-pria/outerwear-pria/jaket-pria        125000
86590          fashion-pria/outerwear-pria/jaket-pria        125000
64620     fashion-wanita/perhiasan-wanita/bros-wanita         25000
54451     fashion-wanita/perhiasan-wanita/bros-wanita         25000
53734              buku/buku-hukum/buku-politik-hukum         54000
64544              buku/buku-hukum/buku-politik-hukum         54000
73664          makanan-minuman/makanan-ringan/keripik         11114
60520          makanan-minuman/makanan-ringan/keripik         12349
126902             kesehatan/vitamin-suplemen/calcium        261616
61631              kesehatan/vitamin-suplemen/calcium        261616

       price_original  discountPercentage  \
79466        Rp47.000                   0
65288             NaN                   0
80471        Rp25.000                   0
60715        Rp25.000                   0
10093             NaN                   0
7996              NaN                   0
7976              NaN                   0
10084             NaN                   0
92128             NaN                   0
8155              NaN                   0
88795             NaN                   0
86590             NaN                   0
64620             NaN                   0
54451             NaN                   0
53734             NaN                   0
64544             NaN                   0
73664        Rp12.999                   0
60520        Rp12.999                   0
126902      Rp373.737                   0
61631       Rp373.737                   0

                                           mediaURL_image  \
79466   https://p16-images-sign-sg.tokopedia-static.ne...
65288   https://p16-images-sign-sg.tokopedia-static.ne...
80471   https://p16-images-sign-sg.tokopedia-static.ne...
60715   https://p16-images-sign-sg.tokopedia-static.ne...
10093   https://p16-images-sign-sg.tokopedia-static.ne...
7996    https://p16-images-sign-sg.tokopedia-static.ne...
7976    https://p16-images-sign-sg.tokopedia-static.ne...
10084   https://p16-images-sign-sg.tokopedia-static.ne...
92128   https://p16-images-sign-sg.tokopedia-static.ne...
8155    https://p16-images-sign-sg.tokopedia-static.ne...
88795   https://p16-images-sign-sg.tokopedia-static.ne...
86590   https://p16-images-sign-sg.tokopedia-static.ne...
64620   https://p16-images-sign-sg.tokopedia-static.ne...
54451   https://p16-images-sign-sg.tokopedia-static.ne...
53734   https://p16-images-sign-sg.tokopedia-static.ne...
64544   https://p19-images-sign-sg.tokopedia-static.ne...
73664   https://p16-images-sign-sg.tokopedia-static.ne...
60520   https://p16-images-sign-sg.tokopedia-static.ne...
126902  https://p19-images-sign-sg.tokopedia-static.ne...
61631   https://p19-images-sign-sg.tokopedia-static.ne...

                                     mediaURL_image_fixed  ratingAverage  ...  \
79466   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
65288   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
80471   https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
60715   https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
10093   https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
7996    https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
7976    https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
10084   https://p16-images-sign-sg.tokopedia-static.ne...            4.8  ...
92128   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
8155    https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
88795   https://p16-images-sign-sg.tokopedia-static.ne...            4.5  ...
86590   https://p16-images-sign-sg.tokopedia-static.ne...            4.5  ...
64620   https://p16-images-sign-sg.tokopedia-static.ne...            5.0  ...
54451   https://p16-images-sign-sg.tokopedia-static.ne...            5.0  ...
53734   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
64544   https://p19-images-sign-sg.tokopedia-static.ne...            4.9  ...
73664   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
60520   https://p16-images-sign-sg.tokopedia-static.ne...            4.9  ...
126902  https://p19-images-sign-sg.tokopedia-static.ne...            4.9  ...
61631   https://p19-images-sign-sg.tokopedia-static.ne...            4.9  ...

        isTopAds                                        labelGroups  \
79466      False  [{"position": "ri_product_credibility", "title...
65288      False  [{"position": "ri_product_credibility", "title...
80471      False  [{"position": "ri_product_credibility", "title...
60715      False  [{"position": "ri_product_credibility", "title...
10093      False  [{"position": "ri_product_credibility", "title...
7996       False  [{"position": "ri_product_credibility", "title...
7976       False  [{"position": "ri_product_credibility", "title...
10084      False  [{"position": "ri_product_credibility", "title...
92128      False  [{"position": "ri_product_credibility", "title...
8155       False  [{"position": "ri_product_credibility", "title...
88795      False  [{"position": "ri_product_credibility", "title...
86590      False  [{"position": "ri_product_credibility", "title...
64620      False  [{"position": "ri_product_credibility", "title...
54451      False  [{"position": "ri_product_credibility", "title...
53734      False  [{"position": "ri_product_credibility", "title...
64544      False  [{"position": "ri_product_credibility", "title...
73664      False  [{"position": "ri_product_credibility", "title...
60520      False  [{"position": "ri_product_credibility", "title...
126902     False  [{"position": "ri_product_credibility", "title...
61631      False  [{"position": "ri_product_credibility", "title...

                                             label_titles totalRating  \
79466   8rb+ terjual | Ramadan_extra_seru | Bisa COD |...      2359.0
65288       8rb+ terjual | Bisa COD | Rp42.000 | Bisa COD      2333.0
80471   10rb+ terjual | Ramadan_extra_seru | Hemat s.d...      1929.0
60715   10rb+ terjual | Ramadan_extra_seru | Beli Loka...      1929.0
10093   3rb+ terjual | Hemat s.d  1% Pakai Bonus | Rp6...        70.0
7996    3rb+ terjual | Hemat s.d  1% Pakai Bonus | Rp6...        70.0
7976    5rb+ terjual | Hemat s.d  1% Pakai Bonus | Rp6...       143.0
10084   5rb+ terjual | Hemat s.d  1% Pakai Bonus | Rp6...       143.0
92128                         2rb+ terjual | Rp35.663.800      1074.0
8155                          2rb+ terjual | Rp35.042.400      1074.0
88795   7 terjual | Hemat s.d  1% Pakai Bonus | Rp125....         2.0
86590   7 terjual | Hemat s.d  1% Pakai Bonus | Rp125....         2.0
64620        30+ terjual | Bisa COD | Rp25.000 | Bisa COD         1.0
54451        30+ terjual | Bisa COD | Rp25.000 | Bisa COD         1.0
53734   40+ terjual | Beli Lokal | Hemat s.d  1% Pakai...        16.0
64544   40+ terjual | Hemat s.d  1% Pakai Bonus | Rp54...        16.0
73664   3rb+ terjual | Rp11.114 | Beli Lokal | Hemat s...       371.0
60520   3rb+ terjual | Rp12.349 | Ramadan_extra_seru |...       372.0
126902  750+ terjual | Ramadan_extra_seru | Beli Lokal...       196.0
61631   750+ terjual | Bisa COD | 30% | Rp261.616 | Bi...       196.0

        countReview  image_status  image_source  \
79466        1000.0         200.0     refreshed
65288         995.0         200.0     refreshed
80471         767.0         200.0           NaN
60715         767.0         200.0           NaN
10093          31.0         403.0           NaN
7996           31.0         200.0     refreshed
7976           46.0         200.0     refreshed
10084          46.0         200.0     refreshed
92128         859.0         200.0     refreshed
8155          859.0         200.0     refreshed
88795           2.0         200.0     refreshed
86590           2.0         200.0     refreshed
64620           1.0         200.0     refreshed
54451           1.0         200.0     refreshed
53734           4.0         200.0     refreshed
64544           4.0         200.0     refreshed
73664         113.0         200.0     refreshed
60520         113.0         200.0     refreshed
126902         46.0         200.0     refreshed
61631          46.0         200.0     refreshed

                                         image_local_path  \
79466         output\olehKhas_enriched_images\1652218.jpg
65288       output\khasDaerah_enriched_images\1652218.jpg
80471                                                 NaN
60715                                                 NaN
10093                                                 NaN
7996      output\aksesoriPria_enriched_images\7823934.jpg
7976      output\aksesoriPria_enriched_images\7823984.jpg
10084   output\aksesoriWanita_enriched_images\7823984.jpg
92128          output\parfum_enriched_images\32114907.jpg
8155     output\aksesoriPria_enriched_images\32114907.jpg
88795   output\pakaianAnakCowok_enriched_images\346917...
86590   output\pakaianAnakCewek_enriched_images\346917...
64620      output\khasDaerah_enriched_images\34752708.jpg
54451      output\kainDaerah_enriched_images\34752708.jpg
53734      output\kainDaerah_enriched_images\37523721.jpg
64544      output\khasDaerah_enriched_images\37523721.jpg
73664         output\makanan_enriched_images\40888941.jpg
60520     output\keripikKhas_enriched_images\40888941.jpg
126902  output\vitaminSuplemen_enriched_images\4629853...
61631       output\kesehatan_enriched_images\46298536.jpg

                          source_file          category
79466           olehKhas_enriched.csv          olehKhas
65288         khasDaerah_enriched.csv        khasDaerah
80471           olehKhas_enriched.csv          olehKhas
60715        keripikKhas_enriched.csv       keripikKhas
10093     aksesoriWanita_enriched.csv    aksesoriWanita
7996        aksesoriPria_enriched.csv      aksesoriPria
7976        aksesoriPria_enriched.csv      aksesoriPria
10084     aksesoriWanita_enriched.csv    aksesoriWanita
92128             parfum_enriched.csv            parfum
8155        aksesoriPria_enriched.csv      aksesoriPria
88795   pakaianAnakCowok_enriched.csv  pakaianAnakCowok
86590   pakaianAnakCewek_enriched.csv  pakaianAnakCewek
64620         khasDaerah_enriched.csv        khasDaerah
54451         kainDaerah_enriched.csv        kainDaerah
53734         kainDaerah_enriched.csv        kainDaerah
64544         khasDaerah_enriched.csv        khasDaerah
73664            makanan_enriched.csv           makanan
60520        keripikKhas_enriched.csv       keripikKhas
126902   vitaminSuplemen_enriched.csv   vitaminSuplemen
61631          kesehatan_enriched.csv         kesehatan

[20 rows x 26 columns]

In [22]:
# =========================
# Tampilkan frekuensi tiap 'id' yang duplikat
# =========================
dup_summary = (
    df["id"]
    .value_counts()
    .reset_index()
)

dup_summary.columns = ["id", "jumlah_kemunculan"]
dup_summary = dup_summary[dup_summary["jumlah_kemunculan"] > 1]

print("\nRingkasan 'id' yang duplikat:")
print(dup_summary.head(20))

Ringkasan 'id' yang duplikat:
              id  jumlah_kemunculan
0   102100298545                  6
1   102548246839                  6
2   100323929019                  6
3      770352527                  6
4   102223327228                  6
5   100228997271                  5
6   100005828763                  5
7   100082603169                  5
8   100099423496                  5
9   100269466825                  5
10  100085977958                  5
11   15567247679                  5
12  102310190051                  5
13  100070230741                  5
14  102821926352                  5
15  102777759092                  5
16  100439585776                  5
17  102678422455                  5
18  100675149177                  5
19  100071124683                  5

In [23]:
# Ambil hanya grup id yang duplikat
dup_rows = df[df.duplicated(subset=["id"], keep=False)].sort_values(["id"]).copy()

# Kelompokkan dan lihat ukuran tiap grup
dup_group_size = dup_rows.groupby("id").size().reset_index(name="jumlah_kemunculan")

print(dup_group_size.head(20))

           id  jumlah_kemunculan
0     1652218                  2
1     6652088                  2
2     7823934                  2
3     7823984                  2
4    32114907                  2
5    34691701                  2
6    34752708                  2
7    37523721                  2
8    40888941                  2
9    46298536                  2
10   68113675                  2
11   71004785                  2
12  132299948                  2
13  146084382                  2
14  166232946                  2
15  168528326                  2
16  182511896                  2
17  187319492                  2
18  190023680                  2
19  192470818                  2

In [ ]:
# simpan hasil ke CSV
dup_rows.to_csv("duplicate_rows_by_id.csv", index=False)
dup_summary.to_csv("duplicate_id_summary.csv", index=False)

In [ ]:
# simpan hasil ke CSV juga
dup_rows = df[df.duplicated(subset=["id"])].sort_values("id")
dup_rows.to_csv(r"d:\Kuliah\data TA\olahData\duplicateData_id.csv", index=False, encoding="utf-8-sig")

In [ ]:
# cek baris yang duplikat penuh
full_duplicate_count = df.duplicated().sum()

print("Jumlah duplikat penuh:", full_duplicate_count)

Jumlah duplikat penuh: 0

In [ ]:
# =========================
# Hitung skor kelengkapan hanya pada dup_rows
# =========================
dup_rows = dup_rows.copy()

# rapikan missing value dulu
dup_rows = dup_rows.replace(["", " ", "None", "none", "NULL", "null", "NaN", "nan"], np.nan)

# hitung jumlah kolom terisi per baris
dup_rows["completeness_score"] = dup_rows.notna().sum(axis=1)

dup_rows[["id", "completeness_score"]].head(10)

             id  completeness_score
79466   1652218                  26
65288   1652218                  25
80471   6652088                  24
60715   6652088                  24
10093   7823934                  23
7996    7823934                  25
7976    7823984                  25
10084   7823984                  25
92128  32114907                  25
8155   32114907                  25

In [ ]:
# Pilih 1 record terbaik per id dari dup_rows
dup_rows_sorted = dup_rows.sort_values(
    by=["id", "completeness_score"],
    ascending=[True, False]
).copy()

dup_best = dup_rows_sorted.drop_duplicates(subset=["id"], keep="first").copy()

print("Jumlah record terbaik dari grup duplikat:", len(dup_best))
print("Jumlah id unik pada grup duplikat:", dup_best["id"].nunique())
print("Sisa duplikat id di dup_best:", dup_best["id"].duplicated().sum())

Jumlah record terbaik dari grup duplikat: 6011
Jumlah id unik pada grup duplikat: 6011
Sisa duplikat id di dup_best: 0

In [30]:
# Ambil record duplikat yang dibuang
best_indices = dup_best.index
dup_removed = dup_rows_sorted.loc[~dup_rows_sorted.index.isin(best_indices)].copy()

print("Jumlah record duplikat yang dibuang:", len(dup_removed))
dup_removed.head()

Jumlah record duplikat yang dibuang: 6857

,id,name,url,category_breadcrumb,price_number,price_original,discountPercentage,mediaURL_image,mediaURL_image_fixed,ratingAverage,...,labelGroups,label_titles,totalRating,countReview,image_status,image_source,image_local_path,source_file,category,completeness_score
65288,1652218,Petis Botol Yudhistira ORIGINAL Siap Saji Khas...,https://www.tokopedia.com/tahupetis/petis-siap...,makanan-minuman/bumbu-bahan-masakan/kecap,42000,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.9,...,"[{""position"": ""ri_product_credibility"", ""title...",8rb+ terjual | Bisa COD | Rp42.000 | Bisa COD,2333.0,995.0,200.0,refreshed,output\khasDaerah_enriched_images\1652218.jpg,khasDaerah_enriched.csv,khasDaerah,25
60715,6652088,Keripik Maicih Basreng Level 10 Pedas Rempah O...,https://www.tokopedia.com/geraisnackofficial/k...,makanan-minuman/makanan-ringan/keripik,18900,Rp25.000,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",10rb+ terjual | Ramadan_extra_seru | Beli Loka...,1929.0,767.0,200.0,NaN,NaN,keripikKhas_enriched.csv,keripikKhas,24
10093,7823934,Bahan Aksesoris Kait Kalung Tembaga,https://www.tokopedia.com/de-mote/bahan-akseso...,fashion-wanita/perhiasan-wanita/kalung-wanita,650,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",3rb+ terjual | Hemat s.d 1% Pakai Bonus | Rp6...,70.0,31.0,403.0,NaN,NaN,aksesoriWanita_enriched.csv,aksesoriWanita,23
10084,7823984,Bahan Aksesoris Kait Kalung Gold,https://www.tokopedia.com/de-mote/bahan-akseso...,fashion-wanita/perhiasan-wanita/kalung-wanita,650,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",5rb+ terjual | Hemat s.d 1% Pakai Bonus | Rp6...,143.0,46.0,200.0,refreshed,output\aksesoriWanita_enriched_images\7823984.jpg,aksesoriWanita_enriched.csv,aksesoriWanita,25
8155,32114907,Logam Mulia Antam 10 Gram Sertifikat Press,https://www.tokopedia.com/indo-gold/emas-antam...,logam-mulia,35042400,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.9,...,"[{""position"": ""ri_product_credibility"", ""title...",2rb+ terjual | Rp35.042.400,1074.0,859.0,200.0,refreshed,output\aksesoriPria_enriched_images\32114907.jpg,aksesoriPria_enriched.csv,aksesoriPria,25

In [31]:
# Ambil baris yang dari awal tidak duplikat
non_dup_rows = df[~df.duplicated(subset=["id"], keep=False)].copy()

print("Jumlah baris non-duplikat:", len(non_dup_rows))

Jumlah baris non-duplikat: 115635

In [32]:
# Gabungkan kembali data non-duplikat dengan record terbaik dari grup duplikat
df_clean = pd.concat([non_dup_rows, dup_best], ignore_index=True)

print("Jumlah data akhir:", len(df_clean))
print("Jumlah id unik akhir:", df_clean["id"].nunique())
print("Sisa duplikat berdasarkan id:", df_clean["id"].duplicated().sum())

Jumlah data akhir: 121646
Jumlah id unik akhir: 121646
Sisa duplikat berdasarkan id: 0

In [33]:
# Simpan hasil ke CSV
df_clean.to_csv("nondup_dataset.csv", index=False)
dup_removed.to_csv("dup_removed.csv", index=False)

print("File berhasil disimpan:")
print("- nondup_dataset.csv")
print("- dup_removed.csv")

File berhasil disimpan:
- nondup_dataset.csv
- dup_removed.csv

## Membersihkan Teks
**Input:** Kolom teks seperti `name`, `category_breadcrumb`, `shop_city`, dan `labelGroups`.

**Output:** Kolom baru seperti `name_clean`, `category_clean`, `city_clean`, dan `labelGroups_clean` yang sudah dibersihkan dari karakter tidak diinginkan.

In [4]:
df = pd.read_csv("../olahData/nondup_dataset.csv")
print(df.shape)
df.head()

(121646, 27)

,id,name,url,category_breadcrumb,price_number,price_original,discountPercentage,mediaURL_image,mediaURL_image_fixed,ratingAverage,...,labelGroups,label_titles,totalRating,countReview,image_status,image_source,image_local_path,source_file,category,completeness_score
0,102092883266,(Free Kotak)Ikat Rambut Jepit Rambut Set Anak ...,https://www.tokopedia.com/blissow-tk/free-kota...,fashion-anak-bayi/aksesoris-anak/ikat-rambut-anak,98450,Rp179.000,0,https://p16-images-common-sign-sg.tokopedia-st...,https://p16-images-common-sign-sg.tokopedia-st...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Hemat s.d 1% Pakai Bonus | 45%...,203.0,80.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1020928832...,aksesoriAnak_enriched.csv,aksesoriAnak,26
1,6191416839,Ikat Rambut Karet Pita Anak 18 in 1 Jepit Ramb...,https://www.tokopedia.com/tokomixnmax/ikat-ram...,fashion-anak-bayi/aksesoris-anak/pita-rambut-anak,19990,NaN,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.9,...,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Hemat s.d 1% Pakai Bonus | Rp1...,338.0,50.0,200.0,refreshed,output\aksesoriAnak_enriched_images\6191416839...,aksesoriAnak_enriched.csv,aksesoriAnak,25
2,12451070010,Shinemi - 14pcs / Set Jepitan Rambut Anak Fash...,https://www.tokopedia.com/universalcs/shinemi-...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,9845,Rp9.999,0,https://p16-images-sign-sg.tokopedia-static.ne...,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Campaign | Hemat s.d 1% Pakai ...,349.0,61.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1245107001...,aksesoriAnak_enriched.csv,aksesoriAnak,26
3,100082586008,ByKiddos - Set Aksesories Rambut Anak Isi 18 P...,https://www.tokopedia.com/bykiddos/bykiddos-se...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,22900,Rp39.000,0,https://p16-images-common-sign-sg.tokopedia-st...,https://p16-images-common-sign-sg.tokopedia-st...,4.8,...,"[{""position"": ""ri_product_credibility"", ""title...",1rb+ terjual | Bisa COD | 41% | Rp22.900 | Bis...,180.0,127.0,403.0,NaN,NaN,aksesoriAnak_enriched.csv,aksesoriAnak,24
4,100023249764,Jam Tangan Digital Anak Cute Cantik Cowok Cewe...,https://www.tokopedia.com/sby-storeid/jam-tang...,fashion-anak-bayi/jam-tangan-anak/jam-tangan-d...,13500,NaN,0,https://p16-images-common-sign-sg.tokopedia-st...,https://p16-images-common-sign-sg.tokopedia-st...,4.5,...,"[{""position"": ""ri_product_credibility"", ""title...",9rb+ terjual | Bisa COD | Rp13.500 | Bisa COD,1417.0,713.0,200.0,refreshed,output\aksesoriAnak_enriched_images\1000232497...,aksesoriAnak_enriched.csv,aksesoriAnak,25

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121646 entries, 0 to 121645
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    121646 non-null  int64
 1   name                  121646 non-null  object
 2   url                   121646 non-null  object
 3   category_breadcrumb   121623 non-null  object
 4   price_number          121646 non-null  int64
 5   price_original        64685 non-null   object
 6   discountPercentage    121646 non-null  int64
 7   mediaURL_image        121646 non-null  object
 8   mediaURL_image_fixed  121639 non-null  object
 9   ratingAverage         121621 non-null  float64
 10  shop_id               121646 non-null  int64
 11  shop_name             121646 non-null  object
 12  shop_url              121646 non-null  object
 13  shop_city             121281 non-null  object
 14  shop_tier             121646 non-null  int64
 15  countSold             111085 non-null  float64
 16  isTopAds              121646 non-null  bool
 17  labelGroups           121646 non-null  object
 18  label_titles          121638 non-null  object
 19  totalRating           121582 non-null  float64
 20  countReview           121582 non-null  float64
 21  image_status          118631 non-null  float64
 22  image_source          104151 non-null  object
 23  image_local_path      104151 non-null  object
 24  source_file           121646 non-null  object
 25  category              121646 non-null  object
 26  completeness_score    121646 non-null  int64
dtypes: bool(1), float64(5), int64(6), object(15)
memory usage: 24.2+ MB

In [6]:
df = df.drop(columns=["mediaURL_image_fixed", "isTopAds", "labelGroups", "image_source", "category", "completeness_score"])

In [7]:
# ==========================
# Untuk membersihkan teks
# ==========================
def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()                             # Jadikan semua huruf kecil
    text = re.sub(r"[^a-z0-9\s]", " ", text)        # Ganti semua karakter selain huruf a-z, angka 0-9, dan spasi menjadi spasi
    text = re.sub(r"\s+", " ", text).strip()        # Rapikan spasi berlebihan jadi satu spasi, lalu hapus spasi di awal/akhir
    return text

In [8]:
# Bersihkan kolom ....
df["name_clean"] = df["name"].apply(clean_text)
df["category_clean"] = df["category_breadcrumb"].apply(clean_text)
df["city_clean"] = df["shop_city"].apply(clean_text)

In [9]:
df[["name_clean", "category_clean", "city_clean",]].head()

,name_clean,category_clean,city_clean
0,free kotak ikat rambut jepit rambut set anak p...,fashion anak bayi aksesoris anak ikat rambut anak,jakarta barat
1,ikat rambut karet pita anak 18 in 1 jepit ramb...,fashion anak bayi aksesoris anak pita rambut anak,jakarta barat
2,shinemi 14pcs set jepitan rambut anak fashion ...,fashion anak bayi aksesoris anak jepitan rambu...,jakarta utara
3,bykiddos set aksesories rambut anak isi 18 pcs...,fashion anak bayi aksesoris anak jepitan rambu...,surabaya
4,jam tangan digital anak cute cantik cowok cewe...,fashion anak bayi jam tangan anak jam tangan d...,surabaya

## Normalisasi 
**Input:** Kolom `price_original` yang berisi data harga dalam format string.

**Output:** Kolom `price_original` yang sudah dinormalisasi menjadi tipe data numerik dan kolom `discountPercentage` yang menunjukkan persentase diskon.

In [10]:
# =========================
# normalisasi kolom price_original
# =========================
df["price_original"] = (
    df["price_original"]
        .astype("string")
        .str.replace(r"[^0-9]", "", regex=True)
        .fillna("0")
        .replace("", "0")
        .astype("Int64")
)

In [11]:
# Hitung discountPercentage
df["discountPercentage"] = np.where(
    df["price_original"].notna() & (df["price_original"] > 0),
    ((df["price_original"] - df["price_number"]) / df["price_original"] * 100),
    0                   # ← kalau price_original NaN / 0
)

# Rapikan hasil
df["discountPercentage"] = (
    df["discountPercentage"]
        .round(0)        # bisa ganti round(2)
        .clip(0, 100)    # jaga tetap masuk akal
        .astype(int)     # opsional: jadi integer
)

# cek hasil
df[["price_number", "price_original", "discountPercentage"]].head(10)

   price_number  price_original  discountPercentage
0         98450          179000                  45
1         19990               0                   0
2          9845            9999                   2
3         22900           39000                  41
4         13500               0                   0
5          4790               0                   0
6         28512           49500                  42
7         18999           25999                  27
8         14550               0                   0
9        125000          259000                  52

In [12]:
# ubah ke int
cols = ["countSold", "countReview", "totalRating"]

df[cols] = df[cols].fillna(0).astype("Int64")

In [13]:
df[["countSold", "countReview", "totalRating"]].head(10)

   countSold  countReview  totalRating
0       1000           80          203
1       1000           50          338
2       1000           61          349
3       1000          127          180
4       9000          713         1417
5     100000         4374        13302
6        100           34           35
7        500           42           45
8       2000          132          243
9       7000          261          825

In [14]:
df.head()

,id,name,url,category_breadcrumb,price_number,price_original,discountPercentage,mediaURL_image,ratingAverage,shop_id,...,countSold,label_titles,totalRating,countReview,image_status,image_local_path,source_file,name_clean,category_clean,city_clean
0,102092883266,(Free Kotak)Ikat Rambut Jepit Rambut Set Anak ...,https://www.tokopedia.com/blissow-tk/free-kota...,fashion-anak-bayi/aksesoris-anak/ikat-rambut-anak,98450,179000,45,https://p16-images-common-sign-sg.tokopedia-st...,4.8,7496005361902389348,...,1000,1rb+ terjual | Hemat s.d 1% Pakai Bonus | 45%...,203,80,200.0,output\aksesoriAnak_enriched_images\1020928832...,aksesoriAnak_enriched.csv,free kotak ikat rambut jepit rambut set anak p...,fashion anak bayi aksesoris anak ikat rambut anak,jakarta barat
1,6191416839,Ikat Rambut Karet Pita Anak 18 in 1 Jepit Ramb...,https://www.tokopedia.com/tokomixnmax/ikat-ram...,fashion-anak-bayi/aksesoris-anak/pita-rambut-anak,19990,0,0,https://p16-images-sign-sg.tokopedia-static.ne...,4.9,9203337,...,1000,1rb+ terjual | Hemat s.d 1% Pakai Bonus | Rp1...,338,50,200.0,output\aksesoriAnak_enriched_images\6191416839...,aksesoriAnak_enriched.csv,ikat rambut karet pita anak 18 in 1 jepit ramb...,fashion anak bayi aksesoris anak pita rambut anak,jakarta barat
2,12451070010,Shinemi - 14pcs / Set Jepitan Rambut Anak Fash...,https://www.tokopedia.com/universalcs/shinemi-...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,9845,9999,2,https://p16-images-sign-sg.tokopedia-static.ne...,4.8,6730810,...,1000,1rb+ terjual | Campaign | Hemat s.d 1% Pakai ...,349,61,200.0,output\aksesoriAnak_enriched_images\1245107001...,aksesoriAnak_enriched.csv,shinemi 14pcs set jepitan rambut anak fashion ...,fashion anak bayi aksesoris anak jepitan rambu...,jakarta utara
3,100082586008,ByKiddos - Set Aksesories Rambut Anak Isi 18 P...,https://www.tokopedia.com/bykiddos/bykiddos-se...,fashion-anak-bayi/aksesoris-anak/jepitan-rambu...,22900,39000,41,https://p16-images-common-sign-sg.tokopedia-st...,4.8,7494455525741333085,...,1000,1rb+ terjual | Bisa COD | 41% | Rp22.900 | Bis...,180,127,403.0,NaN,aksesoriAnak_enriched.csv,bykiddos set aksesories rambut anak isi 18 pcs...,fashion anak bayi aksesoris anak jepitan rambu...,surabaya
4,100023249764,Jam Tangan Digital Anak Cute Cantik Cowok Cewe...,https://www.tokopedia.com/sby-storeid/jam-tang...,fashion-anak-bayi/jam-tangan-anak/jam-tangan-d...,13500,0,0,https://p16-images-common-sign-sg.tokopedia-st...,4.5,7494773692768815982,...,9000,9rb+ terjual | Bisa COD | Rp13.500 | Bisa COD,1417,713,200.0,output\aksesoriAnak_enriched_images\1000232497...,aksesoriAnak_enriched.csv,jam tangan digital anak cute cantik cowok cewe...,fashion anak bayi jam tangan anak jam tangan d...,surabaya

In [15]:
df.columns

Index(['id', 'name', 'url', 'category_breadcrumb', 'price_number',
       'price_original', 'discountPercentage', 'mediaURL_image',
       'ratingAverage', 'shop_id', 'shop_name', 'shop_url', 'shop_city',
       'shop_tier', 'countSold', 'label_titles', 'totalRating', 'countReview',
       'image_status', 'image_local_path', 'source_file', 'name_clean',
       'category_clean', 'city_clean'],
      dtype='object')

In [16]:
# Diskon >50% Disebut "super promo" atau flash sale, lebih menarik perhatian.
df["has_promo"] = (
    (df["discountPercentage"] >= 40) |
    (df["label_titles"].str.contains("diskon|hemat|promo", regex=True))
)

df["has_promo"].value_counts()

has_promo
False    83401
True     38245
Name: count, dtype: int64

## XX isTopAds tidak ada XX
“Pada dataset hasil pengambilan data, tidak ditemukan produk yang secara eksplisit diberi label iklan (TopAds) oleh platform e-commerce pada hasil pencarian. Oleh karena itu, seluruh produk diperlakukan sebagai non-iklan dalam analisis.”

“Fitur isTopAds tetap disertakan sebagai antisipasi karena secara desain sistem rekomendasi, iklan merupakan salah satu sumber bias. Namun pada dataset yang digunakan dalam penelitian ini, tidak ditemukan produk dengan label iklan, sehingga fitur tersebut tidak berkontribusi dalam pemodelan.”

In [ ]:
ADS_KEYWORDS = ["iklan", "sponsored", "ads"]

df["isTopAds"] = df["label_titles"].apply(
    lambda x: any(k in x for k in ADS_KEYWORDS)
)

In [ ]:
df["isTopAds"].value_counts()

isTopAds
False    2136
Name: count, dtype: int64

## Menghitung Skor UMKM
**Input:** Kolom seperti `countSold`, `isTopAds`, `shop_tier`, `label_titles`, `name_clean`, dan `shop_name`.

**Output:** Kolom `umkm_score` yang menunjukkan skor UMKM berdasarkan kriteria tertentu dan kolom `is_umkm` yang menunjukkan apakah produk termasuk UMKM atau tidak.

In [18]:
UMKM_KEYWORDS = [
    # identitas & lokal
    "umkm","lokal","daerah","khas","asli","tradisional","nusantara",
    "makassar","toraja","bugis","bali","jogja","solo","bandung","malang","aceh",  # opsional: tambah daerah relevan

    # handmade & craft
    "handmade","hand made","buatan tangan","kerajinan","craft","artisan","rajut","anyaman",
    "batik","tenun","songket","ukir","gerabah","keramik","rotan","bambu",

    # rumahan & produksi kecil
    "home made","homemade","rumahan","home industry","industri rumahan","produksi rumahan",

    # custom/personalized
    "custom","kustom","preorder","pre order","made by order","by order",
]

NON_KEYWORDS = [
    "official","official store","officialstore","toko resmi","store resmi",
    "mall","tokopedia mall","brand store","flagship","flagship store",
    "authorized","authorised","distributor resmi","import","garansi resmi"
]

def make_regex(words):
    pats = []
    for w in words:
        w = w.strip().lower()
        # boundary untuk kata tunggal biar ga false match
        if " " in w:
            pats.append(re.escape(w))
        else:
            pats.append(r"\b" + re.escape(w) + r"\b")
    return re.compile("(" + "|".join(pats) + ")", re.IGNORECASE)

RE_UMKM   = make_regex(UMKM_KEYWORDS)
RE_NON    = make_regex(NON_KEYWORDS)

In [19]:
def umkm_score(row):
    score = 0.0
    reasons = []

    # gabung teks untuk deteksi keyword
    text = " ".join([
        str(row.get("name_clean","") or ""),
        str(row.get("shop_name","") or ""),
        str(row.get("label_titles","") or ""),
        str(row.get("category_clean","") or ""),
        str(row.get("city_clean","") or ""),
    ]).lower()

    # --- penalti kuat non-UMKM ---
    if RE_NON.search(text):
        score -= 4
        reasons.append("official/mall")

    # --- sinyal UMKM dari keyword ---
    if RE_UMKM.search(text):
        score += 2
        reasons.append("umkm_keywords")

    # --- penjualan (skala) ---
    sold = row.get("countSold", np.nan)
    if pd.notna(sold):
        try:
            sold = float(sold)
            if sold < 50_000:
                score += 2
                reasons.append("sold<50k")
            elif sold >= 200_000:
                score -= 2
                reasons.append("sold>=200k")
        except:
            pass

    # --- tier toko ---
    tier = row.get("shop_tier", np.nan)
    if pd.notna(tier):
        try:
            tier = int(tier)
            if tier <= 2:
                score += 1
                reasons.append("tier<=2")
            elif tier >= 3:
                score -= 1
                reasons.append("tier>=3")
        except:
            pass

    # --- label "beli lokal" ---
    if "beli lokal" in text:
        score += 1
        reasons.append("beli_lokal")

    return pd.Series({
        "umkm_score": score,
        "umkm_reasons": "|".join(reasons)
    })

In [23]:
df[["umkm_score","umkm_reasons"]] = df.apply(umkm_score, axis=1)

# threshold (bisa kamu tuning)
df["umkm_label"] = np.where(df["umkm_score"] >= 2, "UMKM", "NON_UMKM")
df["umkm_label"].value_counts()

# df["umkm_label"] = np.where(df["umkm_score"] >= 2, "UMKM",
#                     np.where(df["umkm_score"] <= 0, "NON_UMKM", "AMBIGUOUS"))

# df["umkm_label"].value_counts()

umkm_label
UMKM        78391
NON_UMKM    43255
Name: count, dtype: int64

In [24]:
print("10 Baris Pertama Data yang Telah Dilabel")
print("=" * 100)
print(df[["name", "shop_name", "countSold", "shop_tier", "umkm_score", "umkm_label"]].head(10))

10 Baris Pertama Data yang Telah Dilabel
====================================================================================================
                                                name            shop_name  \
0  (Free Kotak)Ikat Rambut Jepit Rambut Set Anak ...           BLISSOW TK
1  Ikat Rambut Karet Pita Anak 18 in 1 Jepit Ramb...          tokomixnmax
2  Shinemi - 14pcs / Set Jepitan Rambut Anak Fash...   Shinemi Collection
3  ByKiddos - Set Aksesories Rambut Anak Isi 18 P...             bykiddos
4  Jam Tangan Digital Anak Cute Cantik Cowok Cewe...         Sby Store.id
5  Karet rambut 200pcs / Karet rambut Donat Pouch...         Lashop87_NEW
6  ED - PAKET AKSESORIS SET JEPITAN KUNCIRAN IKAT...      Eternal Diary X
7  Mahkota Rangkaian Bunga Anak Headband Putri - ...              RXK ACC
8  ￼18pcs Set Ikat Rambut Sanrio Aksesoris Rambut...  maskermurahsurabaya
9  316Pcs Jepit Rambut Anak Kotak Hadiah Set Keli...            wetech.id

   countSold  shop_tier  umkm_score umkm_label
0       1000          1         3.0       UMKM
1       1000          3         1.0   NON_UMKM
2       1000          3         1.0   NON_UMKM
3       1000          3        -3.0   NON_UMKM
4       9000          3         1.0   NON_UMKM
5     100000          3        -1.0   NON_UMKM
6        100          3         1.0   NON_UMKM
7        500          3         1.0   NON_UMKM
8       2000          1         3.0       UMKM
9       7000          3         1.0   NON_UMKM

In [26]:
df.columns

Index(['id', 'name', 'url', 'category_breadcrumb', 'price_number',
       'price_original', 'discountPercentage', 'mediaURL_image',
       'ratingAverage', 'shop_id', 'shop_name', 'shop_url', 'shop_city',
       'shop_tier', 'countSold', 'label_titles', 'totalRating', 'countReview',
       'image_status', 'image_local_path', 'source_file', 'name_clean',
       'category_clean', 'city_clean', 'has_promo', 'umkm_score',
       'umkm_reasons', 'umkm_label'],
      dtype='object')

In [27]:
df.to_csv("nondup_labeled_dataset.csv", index=False)

In [28]:
# jumlah yang terisi (tidak null / tidak NaN)
filled = df["image_local_path"].notna().sum()
print("image_local_path terisi:", filled)

# jumlah yang kosong (null/NaN)
empty = df["image_local_path"].isna().sum()
print("image_local_path kosong:", empty)

# total baris
print("total baris:", len(df))

image_local_path terisi: 104151
image_local_path kosong: 17495
total baris: 121646